---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: "Application template for Keycloak (Mysql) 2.5.5.Final"
    iconClass: "icon-wildfly"
    tags: "keycloak,java,wildfly,jboss"
    version: "1.0.0"
    "openshift.io/display-name": "Keycloak 2.5.5.Final"
  name: "keycloak-persistent-mysql"
  labels:
    app: "${DATABASE_SERVICE_NAME}"
    group: "org.sistcoop"
message: "A new Keycloak service has been created in your project.\n\n Keycloak Server (Master Realm)\n--------------------\n- Username: ${KEYCLOAK_ADMIN_USER}\n- Password: ${KEYCLOAK_ADMIN_PASSWORD}\n\n Mysql\n--------------------\n- Database: \"${DB_DATABASE}\"\n- Username:${DB_USERNAME}\n- Password: ${DB_PASSWORD}   "
parameters:
  - displayName: "Application Name"
    description: "The name for the application."
    name: APPLICATION_NAME
    value: keycloak
    required: true
  - displayName: "Keycloak Admin Username"
    description: "Keycloak Server admin username"
    name: KEYCLOAK_ADMIN_USER
    from: "[a-zA-Z0-9]{8}"
    generate: expression
    required: true
  - displayName: "Keycloak Admin Password"
    description: "Keycloak Server admin  password"
    name: KEYCLOAK_ADMIN_PASSWORD
    from: "[a-zA-Z0-9]{8}"
    generate: expression
    required: true
  - displayName: "Keycloak Custom http Route Hostname"
    description: "Custom hostname for http service route. Leave blank for default hostname, e.g.: <application-name>.<project>.<default-domain-suffix>"
    name: HOSTNAME_HTTP
    value: ""
    required: false
  - displayName: "Datasource Minimum Pool Size"
    description: "Sets xa-pool/min-pool-size for the configured datasource."
    name: DS_MIN_POOL_SIZE
    required: false
  - displayName: "Datasource Maximum Pool Size"
    description: "Sets xa-pool/max-pool-size for the configured datasource."
    name: DS_MAX_POOL_SIZE
    required: false
  - displayName: "Datasource Transaction Isolation"
    description: "Sets transaction-isolation for the configured datasource."
    name: DS_TX_ISOLATION
    required: false
  - displayName: "Datasource Pool Flush Strategy"
    description: "Sets flush-strategy for the configured datasource."
    name: DS_POOL_FLUSH_STRATEGY
    required: false
  - displayName: "Database Volume Capacity"
    description: "Size of persistent storage for database volume."
    name: "VOLUME_CAPACITY"
    value: "512Mi"
    required: true
  - displayName: "ImageStream Namespace"
    description: "Namespace in which the ImageStreams for Red Hat Middleware images are installed. These ImageStreams are normally installed in the openshift namespace. You should only need to modify this if you've installed the ImageStreams in a different namespace/project."
    name: "IMAGE_STREAM_NAMESPACE"
    value: "openshift"
    required: true
  - displayName: "Mysql Image Version"
    description: "The version of the Mysql image"
    name: "MYSQL_IMAGE_VERSION"
    value: "5.7"
    required": true
  - displayName: "Database Service Name"
    name: "DATABASE_SERVICE_NAME"
    value: "mysql"
    required: true
  - displayName: "Keycloak Database Name"
    description: "Database name"
    name: "DB_DATABASE"
    value: "keycloak"
    required: true
  - displayName: "Database Username"
    description: "Database user name"
    name: "DB_USERNAME"
    from: "user[a-zA-Z0-9]{3}"
    generate: "expression"
    required: true
  - displayName: "Database Password"
    description: "Database user password"
    name: "DB_PASSWORD"
    from: "user[a-zA-Z0-9]{3}"
    generate: "expression"
    required: true
  - displayName: "MySQL Lower Case Table Names"
    description: "Sets how the table names are stored and compared."
    name: "MYSQL_LOWER_CASE_TABLE_NAMES"
    required: false
  - displayName: "MySQL Maximum number of connections"
    description: "The maximum permitted number of simultaneous client connections."
    name: "MYSQL_MAX_CONNECTIONS"
    required: false
  - displayName: "MySQL FullText Minimum Word Length"
    description: "The minimum length of the word to be included in a FULLTEXT index."
    name: "MYSQL_FT_MIN_WORD_LEN"
    required: false
  - displayName: "MySQL FullText Maximum Word Length"
    description: "The maximum length of the word to be included in a FULLTEXT index."
    name: "MYSQL_FT_MAX_WORD_LEN"
    required: false
  - displayName: "MySQL AIO"
    description: "Controls the innodb_use_native_aio setting value if the native AIO is broken."
    name: "MYSQL_AIO"
    required: false
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
        group: "org.sistcoop"
      annotations:
        service.alpha.openshift.io/dependencies: "[{\"name\": \"${DATABASE_SERVICE_NAME}\", \"kind\": \"Service\"}]"
    spec:
      ports:
      - port: 8080
        targetPort: 8080
      selector:
        app: "${APPLICATION_NAME}"
        group: "org.sistcoop"
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${DATABASE_SERVICE_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
        group: "org.sistcoop"
    spec:
      ports:
      - port: 3306
        targetPort: 3306
      selector:
        app: "${DATABASE_SERVICE_NAME}"
        group: "org.sistcoop"
  - kind: Route
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
        group: "org.sistcoop"
    spec:
      host: "${HOSTNAME_HTTP}"
      to:
        kind: Service
        name: "${APPLICATION_NAME}"
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
        group: "org.sistcoop"
    spec:
      dockerImageRepository: "openfact/keycloak-mysql"
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
        group: "org.sistcoop"
    spec:
      strategy:
        type: Rolling
        rollingParams:
          timeoutSeconds: 10800
      triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - "${APPLICATION_NAME}"
          from:
            kind: ImageStreamTag
            name: "${APPLICATION_NAME}:latest"
      replicas: 1
      selector:
        app: "${APPLICATION_NAME}"
      template:
        metadata:
          name: "${APPLICATION_NAME}"
          labels:
            app: "${APPLICATION_NAME}"
            group: "org.sistcoop"
        spec:
          containers:
          - name: "${APPLICATION_NAME}"
            image: "${APPLICATION_NAME}:latest"
            imagePullPolicy: Always
            lifecycle:
              preStop:
                exec:
                  command:
                  - "/opt/jboss/keycloak/bin/jboss-cli.sh"
                  - "-c"
                  - ":shutdown(timeout=60)"
            ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            env:
            - name: KEYCLOAK_USER
              value: "${KEYCLOAK_ADMIN_USER}"
            - name: KEYCLOAK_PASSWORD
              value: "${KEYCLOAK_ADMIN_PASSWORD}"
            - name: DB_ADDR
              value: "${DATABASE_SERVICE_NAME}"
            - name: DB_DATABASE
              value: "${DB_DATABASE}"            
            - name: DS_MIN_POOL_SIZE
              value: "${DS_MIN_POOL_SIZE}"
            - name: DS_MAX_POOL_SIZE
              value: "${DS_MAX_POOL_SIZE}"
            - name: DB_POOL_FLUSH_STRATEGY
              value: "${DS_POOL_FLUSH_STRATEGY}"
            - name: DS_TX_ISOLATION
              value: "${DS_TX_ISOLATION}"
          terminationGracePeriodSeconds: 75
          restartPolicy: Always
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${DATABASE_SERVICE_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
        group: "org.sistcoop"
    spec:
      strategy:
        type: Recreate
      triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - "${DATABASE_SERVICE_NAME}"
          from:
            kind: ImageStreamTag
            name: "mysql:${MYSQL_IMAGE_VERSION}"
            namespace: "${IMAGE_STREAM_NAMESPACE}"
      replicas: 1
      selector:
        app: "${DATABASE_SERVICE_NAME}"
        group: "org.sistcoop"
      template:
        metadata:
          name: "${DATABASE_SERVICE_NAME}"
          labels:
            app: "${DATABASE_SERVICE_NAME}"
            group: "org.sistcoop"
        spec:
          terminationGracePeriodSeconds: 60
          containers:
          - name: "${DATABASE_SERVICE_NAME}"
            image: "mysql"
            imagePullPolicy: Always
            ports:
            - containerPort: 3306
              protocol: TCP
            volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: "${DATABASE_SERVICE_NAME}-pvol"
            env:
            - name: MYSQL_USER
              value: "${DB_USERNAME}"
            - name: MYSQL_PASSWORD
              value: "${DB_PASSWORD}"
            - name: MYSQL_DATABASE
              value: "${DB_DATABASE}"
            - name: MYSQL_LOWER_CASE_TABLE_NAMES
              value: "${MYSQL_LOWER_CASE_TABLE_NAMES}"  
            - name: MYSQL_MAX_CONNECTIONS
              value: "${MYSQL_MAX_CONNECTIONS}"
            - name: MYSQL_FT_MIN_WORD_LEN
              value: "${MYSQL_FT_MIN_WORD_LEN}"
            - name: MYSQL_FT_MAX_WORD_LEN
              value: "${MYSQL_FT_MAX_WORD_LEN}"
            - name: MYSQL_AIO
              value: "${MYSQL_AIO}"
          volumes:
          - name: "${DATABASE_SERVICE_NAME}-pvol"
            persistentVolumeClaim:
              claimName: "${DATABASE_SERVICE_NAME}-claim"
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: "${DATABASE_SERVICE_NAME}-claim"
      labels:
        app: "${APPLICATION_NAME}"
        group: "org.sistcoop"
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "${VOLUME_CAPACITY}"