---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: "Application template for Keycloak 2.5.5.Final"
    iconClass: "icon-wildfly"
    tags: "keycloak,java,wildfly,jboss"
    version: "1.0.0"
    "openshift.io/display-name": "Keycloak 2.5.5.Final"
  name: "keycloak-ephemeral"
  labels:
    app: "${APPLICATION_NAME}-ephemeral"
    group: "org.sistcoop"
message: "A new Keycloak service has been created in your project.\n\n Keycloak Server (Master Realm)\n--------------------\n- Username: ${KEYCLOAK_ADMIN_USER}\n- Password: ${KEYCLOAK_ADMIN_PASSWORD}"
parameters:
  - displayName: "Application Name"
    description: "The name for the application."
    name: APPLICATION_NAME
    value: keycloak
    required: true
  - displayName: "Keycloak Admin Username"
    description: "Keycloak Server admin username"
    name: KEYCLOAK_ADMIN_USER
    from: "[a-zA-Z0-9]{8}"
    generate: expression
    required: true
  - displayName: "Keycloak Admin Password"
    description: "Keycloak Server admin  password"
    name: KEYCLOAK_ADMIN_PASSWORD
    from: "[a-zA-Z0-9]{8}"
    generate: expression
    required: true
  - displayName: "Keycloak Custom http Route Hostname"
    description: "Custom hostname for http service route. Leave blank for default hostname, e.g.: <application-name>.<project>.<default-domain-suffix>"
    name: HOSTNAME_HTTP
    value: ""
    required: false
  - displayName: "Keycloak Datasource Minimum Pool Size"
    description: "Sets xa-pool/min-pool-size for the configured datasource."
    name: KEYCLOAK_DS_MIN_POOL_SIZE
    required: false
  - displayName: "Keycloak Datasource Maximum Pool Size"
    description: "Sets xa-pool/max-pool-size for the configured datasource."
    name: KEYCLOAK_DS_MAX_POOL_SIZE
    required: false
  - displayName: "Keycloak Datasource Transaction Isolation"
    description: "Sets transaction-isolation for the configured datasource."
    name: KEYCLOAK_DS_TX_ISOLATION
    required: false
  - displayName: "Keycloak Datasource Pool Flush Strategy"
    description: "Sets flush-strategy for the configured datasource."
    name: KEYCLOAK_DS_POOL_FLUSH_STRATEGY
    required: false
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}-ephemeral"
        group: "org.sistcoop"
    spec:
      ports:
      - name: "8080-tcp"
        port: 8080
        targetPort: 8080
        protocol: TCP
      selector:
        app: "${APPLICATION_NAME}-ephemeral"
        group: "org.sistcoop"
  - kind: Route
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}-ephemeral"
        group: "org.sistcoop"
    spec:
      host: "${HOSTNAME_HTTP}"
      to:
        kind: Service
        name: "${APPLICATION_NAME}"
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}-ephemeral"
        group: "org.sistcoop"
    spec:
      dockerImageRepository: "openfact/keycloak"
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}-ephemeral"
        group: "org.sistcoop"
    spec:
      strategy:
        type: Rolling
        rollingParams:
          timeoutSeconds: 10800
      triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - "${APPLICATION_NAME}"
          from:
            kind: ImageStreamTag
            name: keycloak:latest
      replicas: 1
      selector:
        app: "${APPLICATION_NAME}-ephemeral"
      template:
        metadata:
          labels:
            app: "${APPLICATION_NAME}-ephemeral"
            group: "org.sistcoop"
        spec:
          containers:
          - name: "${APPLICATION_NAME}"
            image: keycloak:latest
            imagePullPolicy: Always
            lifecycle:
              preStop:
                exec:
                  command:
                  - "/opt/jboss/keycloak/bin/jboss-cli.sh"
                  - "-c"
                  - ":shutdown(timeout=60)"
            ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            env:
            - name: KEYCLOAK_USER
              value: "${KEYCLOAK_ADMIN_USER}"
            - name: KEYCLOAK_PASSWORD
              value: "${KEYCLOAK_ADMIN_PASSWORD}"
            - name: DS_MIN_POOL_SIZE
              value: "${KEYCLOAK_DS_MIN_POOL_SIZE}"
            - name: DS_MAX_POOL_SIZE
              value: "${KEYCLOAK_DS_MAX_POOL_SIZE}"
            - name: DB_POOL_FLUSH_STRATEGY
              value: "${KEYCLOAK_DS_POOL_FLUSH_STRATEGY}"
            - name: DS_TX_ISOLATION
              value: "${KEYCLOAK_DS_TX_ISOLATION}"
          terminationGracePeriodSeconds: 75
          restartPolicy: Always