apiVersion: v1
kind: Template
labels:
  template: s2i-keycloak
metadata:
  annotations:
    description: Application template for s2i-keycloak
    iconClass: icon-java
    tags: s2i,keycloak,sso,java,wildfly,jboss
    version: 1.0.0.Final
    openshift.io/display-name: s2i-keycloak
  name: s2i-keycloak
message: A new Service called ${APPLICATION_NAME} has been created in your project
objects:
- kind: Route
  apiVersion: v1
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      group: org.keycloak
    name: ${APPLICATION_NAME}
  spec:
    to:
      kind: Service
      name: ${APPLICATION_NAME}
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      group: org.keycloak
    name: ${APPLICATION_NAME}    
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${APPLICATION_NAME}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
      group: org.keycloak
  spec:
    strategy:
      type: Rolling
      rollingParams:
        timeoutSeconds: 10800
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    template:
      metadata:
        name: ${APPLICATION_NAME}
        labels:
          app: ${APPLICATION_NAME}
          group: org.keycloak
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - name: ${APPLICATION_NAME}
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          ports:
          - name: 8080-tcp
            containerPort: 8080
            protocol: TCP
          env:
          - name: DATASOURCE
            value: ${DATASOURCE}
          - name: WAR_NAME
            value: ${WAR_NAME}
          - name: KEYCLOAK_SECURE_DEPLOYMENT_ATTRS
            value: ${KEYCLOAK_SECURE_DEPLOYMENT_ATTRS}
        terminationGracePeriodSeconds: 75
        restartPolicy: Always
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: s2i-keycloak-wildfly-101-adapter
    labels:
      app: ${APPLICATION_NAME}
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/imported-from: carlosthe19916/s2i-keycloak-wildfly-101-adapter
      from:
        kind: DockerImage
        name: carlosthe19916/s2i-keycloak-wildfly-101-adapter
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec: {}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    source:
      type: Git
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-keycloak-wildfly-101-adapter:latest
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest  
    triggers:
    - type: GitHub
      github:
        secret: 52SM2bSykCPjly44uNjy
    - type: Generic
      generic:
        secret: Oe9qdANPg0zXDb1stZyi
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
parameters:
- description: Application Name
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
- description: Git Repo url
  displayName: Git repo url
  name: GIT_REPO
  value: https://github.com/openfact/openfact.git
  required: true
- description: Datasource Name
  displayName: Datasource Name
  name: DATASOURCE
  value: OpenfactDS
  required: true
- description: War Name
  displayName: War Name
  name: WAR_NAME
  value: ROOT
  required: true
- description: Subsystem
  displayName: Subsystem
  name: KEYCLOAK_SECURE_DEPLOYMENT_ATTRS
  value: auth-server-url=http://localhost:8080/auth,realm=myrealm,resource=sample-application
  required: true