apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-gluster-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: openfact-glusterfs-cluster
    path: myVol1
    readOnly: false
  persistentVolumeReclaimPolicy: Retain