---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: "Application template for Openfact 1.0.0.Final"
    iconClass: "icon-wildfly"
    tags: "openfact,java,wildfly,jboss"
    version: "1.0.0"
    "openshift.io/display-name": "Openfact 1.0.0.Final"
  name: "openfact-ephemeral"
  labels:
    app: "${APPLICATION_NAME}-ephemeral"
    group: "org.sistcoop"
message: "A new Openfact service has been created in your project.\n\n Openfact Server\n--------------------\n Server Auth URL: ${KEYCLOAK_AUTH_SERVER_URL}"
parameters:
  - displayName: "Application Name"
    description: "The name for the application."
    name: APPLICATION_NAME
    value: openfact
    required: true
  - displayName: "Keycloak Server Auth URL"
    description: "Keycloak Server Auth URL"
    name: KEYCLOAK_AUTH_SERVER_URL
    required: true  
  - displayName: "Custom http Route Hostname"
    description: "Custom hostname for http service route. Leave blank for default hostname, e.g.: <application-name>.<project>.<default-domain-suffix>"
    name: HOSTNAME_HTTP
    value: ""
    required: false
  - displayName: "Datasource Minimum Pool Size"
    description: "Sets xa-pool/min-pool-size for the configured datasource."
    name: DS_MIN_POOL_SIZE
    required: false
  - displayName: "Datasource Maximum Pool Size"
    description: "Sets xa-pool/max-pool-size for the configured datasource."
    name: DS_MAX_POOL_SIZE
    required: false
  - displayName: "Datasource Transaction Isolation"
    description: "Sets transaction-isolation for the configured datasource."
    name: DS_TX_ISOLATION
    required: false
  - displayName: "Datasource Pool Flush Strategy"
    description: "Sets flush-strategy for the configured datasource."
    name: DS_POOL_FLUSH_STRATEGY
    required: false
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}-ephemeral"
        group: "org.sistcoop"
    spec:
      ports:
      - name: "8080-tcp"
        port: 8080
        targetPort: 8080
        protocol: TCP
      selector:
        app: "${APPLICATION_NAME}-ephemeral"
        group: "org.sistcoop"
  - kind: Route
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}-ephemeral"
        group: "org.sistcoop"
    spec:
      host: "${HOSTNAME_HTTP}"
      to:
        kind: Service
        name: "${APPLICATION_NAME}"
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}-ephemeral"
        group: "org.sistcoop"
    spec:
      dockerImageRepository: "openfact/openfact"
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}-ephemeral"
        group: "org.sistcoop"
    spec:
      strategy:
        type: Rolling
        rollingParams:
          timeoutSeconds: 10800
      triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - "${APPLICATION_NAME}"
          from:
            kind: ImageStreamTag
            name: "${APPLICATION_NAME}:latest"
      replicas: 1
      selector:
        app: "${APPLICATION_NAME}-ephemeral"
      template:
        metadata:
          labels:
            app: "${APPLICATION_NAME}-ephemeral"
            group: "org.sistcoop"
        spec:
          containers:
          - name: "${APPLICATION_NAME}"
            image: "${APPLICATION_NAME}:latest"
            imagePullPolicy: Always
            lifecycle:
              preStop:
                exec:
                  command:
                  - "/opt/jboss/wildfly/bin/jboss-cli.sh"
                  - "-c"
                  - ":shutdown(timeout=60)"
            ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            env:
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "${KEYCLOAK_AUTH_SERVER_URL}"
          terminationGracePeriodSeconds: 75
          restartPolicy: Always