kind: Template
apiVersion: v1
metadata:
  name: "keycloak"
  annotations:
    openshift.io/display-name: "Keycloak (Openfact)"
    description: "Keycloak server with openfact realm pre configured.\n\nFor more information see https://github.com/openfact/openfact"
    tags: "keycloak,openfact,wildfly,jboss,ubl"
    iconClass: "icon-wildfly"    
message: "Your admin credentials are:\n -Username: ${KEYCLOAK_USER}\n -Password: ${KEYCLOAK_PASSWORD}"
labels:
  application: "keycloak"
parameters:
  - name: KEYCLOAK_USER
    description: "Keycloak admin username"
    value: "admin"
    required: true
  - name: KEYCLOAK_PASSWORD
    description: "Keycloak admin password"
    generate: expression
    from: "[a-zA-Z0-9]{12}"
    required: true
objects:
  - kind: Service
    apiVersion: v1    
    metadata:
      name: "keycloak"
      annotations:
        description: "Exposes and load balances the application pods"
    spec:
      ports:
        - name: "keycloak"
          port: 8080
          targetPort: 8080
      selector:
        name: "keycloak"
   