apiVersion: v1
kind: Endpoints
metadata:
  name: openfact-glusterfs-cluster
subsets:
  - addresses:
      - ip: 192.168.1.6
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.1.6
    ports:
      - port: 1