apiVersion: v1
kind: Template
labels:
  template: openfact-web-console
metadata:
  annotations:
    description: Application template for openfact-web-console
    iconClass: icon-java
    tags: openfact,nodejs,ubl
    version: 1.0.0.Final
    openshift.io/display-name: Openfact-Web-Console
  name: openfact-web-console
message: A new Openfact-Web-Console has been created in your project
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: nodejs-6-centos7
    labels:
      app: openfact-web-console
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/imported-from: centos/nodejs-6-centos7
      from:
        kind: DockerImage
        name: centos/nodejs-6-centos7
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: openfact-web-console
    labels:
      app: openfact-web-console
  spec: {}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: openfact-web-console
    labels:
      app: openfact-web-console
  spec:
    source:
      type: Git
      git:
        uri: https://github.com/openfact/openfact-web-console.git
        ref: master
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs-6-centos7:latest
    output:
      to:
        kind: ImageStreamTag
        name: openfact-web-console:latest  
    triggers:
    - type: GitHub
      github:
        secret: 52SM2bSykCPjly44uNjy
    - type: Generic
      generic:
        secret: Oe9qdANPg0zXDb1stZyi
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: openfact-web-console
    labels:
      app: openfact-web-console
  spec:
    replicas: 1
    selector:
      app: openfact-web-console
      deploymentconfig: openfact-web-console
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600 
    template:
      metadata:
        labels:
          app: openfact-web-console
          deploymentconfig: openfact-web-console
        name: openfact-web-console
      spec:        
        containers:
        - name: openfact-web-console
          image: openfact-web-console
          imagePullPolicy: Always
          env:
          - name: KEYCLOAK_URL
            value: http://keycloak-${HOSTNAME_SUFFIX}
          - name: KEYCLOAK_REALM
            value: ${KEYCLOAK_REALM}          
          - name: KEYCLOAK_CLIENT_ID
            value: ${KEYCLOAK_CLIENT_ID}
          - name: KEYCLOAK_PUBLIC_KEY
            value: ${KEYCLOAK_PUBLIC_KEY}
          - name: OPENFACT_ENDPOINT
            value: http://openfact-${HOSTNAME_SUFFIX}
          - name: HOSTNAME_HTTP
            value: openfact-web-console:8080
          ports:
          - name: 8080-http
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}          
          terminationMessagePath: /dev/termination-log
        restartPolicy: Always
        dnsPolicy: ClusterFirst
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - openfact-web-console
        from:
          kind: ImageStreamTag
          name: openfact-web-console:latest      
    - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: openfact-web-console
      application: openfact-web-console
    name: openfact-web-console
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: openfact-web-console
- kind: Route
  apiVersion: v1
  metadata:
    name: openfact-web-console
  spec:
    to:
      kind: Service
      name: openfact-web-console
parameters:
  - description: Hostname suffix used for routes e.g. openfact-<HOSTNAME_SUFFIX> inventory-<HOSTNAME_SUFFIX>
    displayName: Hostname suffix used for routes
    name: HOSTNAME_SUFFIX
    required: true
  - description: Keycloak realm
    displayName: Keycloak realm
    name: KEYCLOAK_REALM
    value: openfact
    required: true
  - description: Keycloak Client Id
    displayName: Keycloak Cliend Id
    name: KEYCLOAK_CLIENT_ID
    value: openfact-web-console
    required: true
  - description: Keycloak Public Key
    displayName: Keycloak Public Key
    name: KEYCLOAK_PUBLIC_KEY