apiVersion: v1
kind: Template
labels:
  template: openfact-web-console
metadata:
  annotations:
    description: Application template for ${APPLICATION_NAME}
    iconClass: icon-java
    tags: openfact,nodejs,ubl
    version: 1.0.0.Final
    openshift.io/display-name: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}
message: A new ${APPLICATION_NAME} has been created in your project
objects:
- kind: Route
  apiVersion: v1
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    to:
      kind: Service
      name: ${APPLICATION_NAME}
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${APPLICATION_NAME}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600 
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:        
        containers:
        - name: ${APPLICATION_NAME}
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          env:
          - name: KEYCLOAK_URL
            value: ${KEYCLOAK_URL}
          - name: KEYCLOAK_REALM
            value: ${KEYCLOAK_REALM}
          - name: KEYCLOAK_USERNAME
            value: ${KEYCLOAK_ADMIN_USERNAME}
          - name: KEYCLOAK_PASSWORD
            value: ${KEYCLOAK_ADMIN_PASSWORD}
          - name: KEYCLOAK_CLIENT_ID
            value: ${APPLICATION_NAME}
          - name: HOSTNAME_HTTP
            value: ${APPLICATION_NAME}:8080
          - name: OPENFACT_ENDPOINT
            value: ${OPENFACT_ENDPOINT}
          ports:
          - name: 8080-http
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
        restartPolicy: Always
        dnsPolicy: ClusterFirst        
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest      
    - type: ConfigChange
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: nodejs-6-centos7
    labels:
      app: ${APPLICATION_NAME}
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/imported-from: centos/nodejs-6-centos7
      from:
        kind: DockerImage
        name: centos/nodejs-6-centos7
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec: {}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    source:
      type: Git
      git:
        uri: https://github.com/openfact/openfact-web-console.git
        ref: master
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs-6-centos7:latest
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest  
    triggers:
    - type: GitHub
      github:
        secret: 52SM2bSykCPjly44uNjy
    - type: Generic
      generic:
        secret: Oe9qdANPg0zXDb1stZyi
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
parameters:
  - description: Application Name
    displayName: Application Name
    name: APPLICATION_NAME
    value: openfact-web-console
    required: true
  - description: Keycloak Url
    displayName: Keycloak Url
    name: KEYCLOAK_URL
    required: true
  - description: Keycloak realm
    displayName: Keycloak realm
    name: KEYCLOAK_REALM
    value: openfact
    required: true
  - description: Keycloak Admin Username
    displayName: Keycloak Admin Username
    name: KEYCLOAK_ADMIN_USERNAME    
    required: true
  - description: Keycloak Admin Password
    displayName: Keycloak Admin Password
    name: KEYCLOAK_ADMIN_PASSWORD
    required: true
  - description: Openfact Endpoint Url
    displayName: Openfact Endpoint Url
    name: OPENFACT_ENDPOINT
    required: true